[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
s_rgb_stake = "FAimDhcwrK9hikkkFnLx3FXs32ZBk2kw8kwzbLJH8AcV"
s_rgb_craft = "G4Wm9es5xZoZLpyzoFHrtgM4Vmo84CenCSrCK6ZxDSmf"
s_rgb_paint = "BHaigrDd4Ei5ok5XnoNCxzGCGeK9T9RAQtyWKFphGnhi"

[features]
seeds = false
skip-lint = false

[registry]
url = "https://api.apr.dev"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
